name: Build and Deploy ASP.NET Core API with Swagger

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AZURE_WEBAPP_NAME: przychodnia
      AZURE_WEBAPP_PACKAGE_PATH: ./Przychodnia.API/publish
      CONFIGURATION: Release
      DOTNET_VERSION: '8.0.x'
      SWAGGER_DLL: ./Przychodnia.API/bin/Release/net8.0/Przychodnia.API.dll
      SWAGGER_OUTPUT: ./Przychodnia.API/publish/swagger.json
      SWAGGER_VERSION: v1

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration ${{ env.CONFIGURATION }} --no-restore

      - name: Publish
        run: dotnet publish Przychodnia.API/Przychodnia.API.csproj -c ${{ env.CONFIGURATION }} -o ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: Install Swashbuckle CLI
        run: dotnet tool install --global Swashbuckle.AspNetCore.Cli --version 6.5.0

      - name: Generate Swagger
        run: |
          swagger tofile --output "${{ env.SWAGGER_OUTPUT }}" "${{ env.SWAGGER_DLL }}" "${{ env.SWAGGER_VERSION }}"

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
